server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment_routh #payment_route  #路由ID，没有固定规则的但要求唯一，建议配合服务名
#          uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
#            - Path=/payment/get/**  #断言，路径相匹配的进行路由
             - Path=/payment/lb/**
        - id: payment_routh2 #payment_route #路由的ID,没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001
          uri: lb://cloud-payment-service  #匹配后的提供服务的路由地址
          predicates:
            - Path=/payment/lb/**  #断言,路径向匹配的进行路由
#            - After=time
#            - Cookie=username,zyp
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db2023?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
