server:
  port: 9003
spring:
  application:
    name: nacos-payment-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db2023?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  cloud:
    nacos:
      discovery:
        # Nacos\u4F5C\u4E3A\u670D\u52A1\u4E2D\u5FC3\u7684\u5730\u5740
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
