server:
  port: 83
spring:
  application:
    name: nacos-order-consumer
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db2023?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
#        消费者要去访问的微服务名称（注册成功进nacos微服务提供者）
service-url:
  nacos-user-service: http://nacos-payment-provider