server:
  port: 80
spring:
  application:
    name: order-feign-consumer
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db2023?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:7001/eureka
      # defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka #集群版
logging:
  level:
#    feign日志以什么级别监控接口
    com.atguigu.springcloud.service.PaymentFeignService: debug

